Traceback (most recent call last):
  File "utils/create_lang_labels.py", line 11, in <module>
    df = read_data_to_df("data/data_half_slice_2col.csv")
  File "utils/create_lang_labels.py", line 5, in read_data_to_df
    return pd.read_csv(path)
  File "/cluster/scratch/oovcharenko/dsl_hate_speech/python_venv/lib64/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/cluster/scratch/oovcharenko/dsl_hate_speech/python_venv/lib64/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cluster/scratch/oovcharenko/dsl_hate_speech/python_venv/lib64/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/cluster/scratch/oovcharenko/dsl_hate_speech/python_venv/lib64/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cluster/scratch/oovcharenko/dsl_hate_speech/python_venv/lib64/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_half_slice_2col.csv'
